installed_at: '2026-08-16T16:51:23+00:00'
skill_id: git/api-design
git_repo: https://github.com/vekzz-dev/opencode-skills
skill_path: C:\Users\Asus\AppData\Local\Temp\skilz-git-d8rm10mf\api-design
git_sha: 74afa310c8e45d353ff5f96f1c4ce474e3051379
skilz_version: 1.10.0
install_mode: copy
canonical_path: null
