installed_at: '2026-08-16T16:46:46+00:00'
skill_id: git/mastering-postgresql
git_repo: https://github.com/SpillwaveSolutions/mastering-postgresql-agent-skill
skill_path: C:\Users\Asus\AppData\Local\Temp\skilz-git-ep63fo3q\mastering-postgresql
git_sha: 2a713e98b0a4618c51605da401f2cfe5e4b8e3ea
skilz_version: 1.10.0
install_mode: copy
canonical_path: null
